<?php $this->load->view('admin/theme/message'); ?>
<?php 
if($this->session->userdata('domain_verified')=='success')
echo '<h4 style="margin:0"><div class="alert alert-success text-center"> <i class="fa fa-check"></i> '.$this->lang->line("Domain has been verified successfully.").'</div></h4>';
if($this->session->userdata('domain_verified')=='fail')
echo '<h4 style="margin:0"><div class="alert alert-danger text-center"> <i class="fa fa-remove"></i> '.$this->lang->line("Domain has been failed to verify.").'</div></h4>';
if($this->session->userdata('domain_verified')=='noaccess')
echo '<h4 style="margin:0"><div class="alert alert-danger text-center"> <i class="fa fa-remove"></i> '.$this->lang->line("Domain has been failed to verify.").'<br>'.$this->lang->line("HTTP Error 406. An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.").'</div></h4>';
$this->session->unset_userdata('domain_verified');
?>
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1> <?php echo$this->lang->line("Domain List");?> </h1>  
</section>

<!-- Main content -->
<section class="content">  
  <div class="row">
    <div class="col-xs-12">
        <div class="grid_container" style="width:100%; height:700px;">
            <table 
            id="tt"  
            class="easyui-datagrid" 
            url="<?php echo base_url()."imgclick_custom_domain/domain_data"; ?>" 
            
            pagination="true" 
            rownumbers="true" 
            toolbar="#tb" 
            pageSize="100" 
            pageList="[5,10,20,50,100,200]"  
            fit= "true" 
            fitColumns= "true" 
            nowrap= "true" 
            view= "detailview"
            idField="id"
            >
            
                <thead>
                    <tr>                                       
                        <!-- <th field="protocol" sortable="true"><?php echo $this->lang->line("protocol"); ?></th> -->
                        <th field="action_controller_url" formatter="action_controller_url" sortable="true"><?php echo $this->lang->line("redirecting script URL"); ?></th>   
                        <!-- <th field="is_verified" formatter="is_verified" align="center" sortable="true"><?php echo $this->lang->line("verified"); ?></th> -->
                         <th field="verify" formatter='verify'><?php echo $this->lang->line("verify"); ?></th>
                         <th field="category"><?php echo $this->lang->line("category"); ?></th>
                        <th field="view" formatter='action_column'><?php echo $this->lang->line("delete"); ?></th>                    
                    </tr>
                </thead>
            </table>                        
         </div>
  
       <div id="tb" style="padding:3px">
           <!--  <?php if ($this->session->userdata('user_type')== 'Admin' || in_array(110,$this->module_access)) { ?>
              <a class="btn btn-primary"  href="<?php echo site_url('imgclick_custom_domain/add_domain');?>">
                  <i class="fa fa-plus-circle"></i> <?php echo $this->lang->line("add"); ?>
              </a> 
            <?php } ?>  -->
            <br/>      
            <br/>      
        </div>
    </div>
  </div>   
</section>

<script>       
    var base_url="<?php echo site_url(); ?>" ;

    function action_column(value,row,index)
    {               
        var delete_url=base_url+'imgclick_custom_domain/delete_domain/'+row.id;
        var delete_str="<?php echo $this->lang->line('delete');?>";
        var str="";   
        str=str+"<a onclick=\"return confirm('"+'<?php echo $this->lang->line("are you sure that you want to delete this record?"); ?>'+"')\" style='cursor:pointer' class='btn btn-danger' title='"+delete_str+"' href='"+delete_url+"'><i class='fa fa-trash'></i>  "+delete_str+"</a>";
   		
   		 return str;
    }     


    function is_verified(value,row,index)
    {   
        if(value=='1') return "<i class='fa fa-check' style='color:green;'></i>";            
        else return "<i class='fa fa-close' style='color:red;'></i>";     
    }

    function action_controller_url(value,row,index)
    {   
        return "<a target='_BLANK' href='"+row.protocol+row.action_controller_url+"'>"+row.protocol+row.action_controller_url+"</a>";    
    } 

    function verify(value,row,index)
    {   
        if(row.is_verified=='0')
        return "<a class='btn btn-warning btn-sm' href='"+base_url+'imgclick_custom_domain/verify_domain/'+row.id+"'><i class='fa fa-flag'></i> <?php echo $this->lang->line('Verify Now')?></a>"; 
        else return "<span class='label label-success'> <i class='fa fa-check'></i> <?php echo $this->lang->line('already verified')?></span>";   
    } 



</script>

